### ISSUE TITLE
Unable to launch examples

### ISSUE THREAD

**Issue by dsvensson** [RibirX/Ribir#255]
**Problem**
none of the examples work

**Steps To Reproduce**
1. Install Ubuntu 22.10 with 
2. Install GPU driver 4.6.0 NVIDIA 525.78.01
4. Enable Wayland
5. Build with examples
6. Observe: `thread 'main' panicked at 'Error in Surface::configure: requested format Bgra8UnormSrgb is not in list of supported formats: [Bgra8Unorm]'`

Changing the format requested to `Bgra8Unorm` makes the examples work, although with fairly poor font rendering, but that's probably a separate issue. Srgb sounds HDR-related?

Or paste reproducible error codes:

**Expected behavior**
Examples work.

**Screenshots**
N/A

**Environment:**
 - Ribir version: `master`
 - Rust version: `nightly`
 - OS, if relevant: Ubuntu 22.10
 - Browser and version, if relevant: -

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by wjian23** [comment]
Welcome and Thanks @zoechi  :)
We will fix it use Bgra8Unorm instead, it's more common. 
And the poor font rendering, you can raise another issue and give a picture
