### ISSUE TITLE
CSS as Bytecode

### ISSUE THREAD

**Issue by JADSN1894** [RibirX/Ribir#307]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I like very of the approach of using Flutter concepts to mount the UI. I would like something following the concept of CSS  as bytecode like this video: [CSS As BYTECODE](https://www.youtube.com/watch?v=w4_1SagLY94) that uses the [elm-ui](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/) for Elm language to achieve this goal.

**Describe alternatives you've considered**
[async-ui](https://github.com/wishawa/async_ui)
[concoct](https://github.com/concoct-rs/concoct)
[frui](https://github.com/fruiframework/frui)
[rid](https://thlorenz.com/rid-site/)

**Additional context**
As a suggestion, it would be good if put the concepts together.

**Comment by zoechi** [comment]
What of this do you think you can't do currently, except that Ribir currently doesn't support HTML (as far as I know)?

**Comment by JADSN1894** [comment]
For while just continue with abstractions like Column or Row used in Flutter.
Developer don't worry about CSS and JS.

**Comment by M-Adoo** [comment]
@JADSN1894 I don't know much about "CSS As Bytecode", and sorry for having no time to learn it and watch the video you provided in its entirety, but `Ribir`  have no plan to support a style language like CSS to describe the presentation.  We use layout widget and theme to control the visual style of widget. The `theme` is also rust code.  So, I don't know if it satisfies "CSS As Bytecode".

**Comment by JADSN1894** [comment]
The  _use layout widget and theme to control the visual style of widget_ is an excellent approach.
Ribir uses the  built-in widgets `h_align` and `v_algin` to center widgets  horizontally and vertically.
It's good, because developer does not need to worry about is used Flexbox or Grid behind the scenes.

**Comment by JADSN1894** [comment]
What is the planning of Ribir for targeting the web without no plan in supporting languages like HTML and CSS?

**Comment by M-Adoo** [comment]
> What is the planning of Ribir for targeting the web without no plan in supporting languages like HTML and CSS?

We'll render by WebGL or WebGPU.
