### ISSUE TITLE
Transition to Stable Rust Version

### ISSUE THREAD

**Issue by M-Adoo** [RibirX/Ribir#523]
Over the past half year, we've eliminated many of the nightly features previously used in Ribir's development. As a result, we no longer need to rely on Rust's nightly version. It's time to transition to the stable version of Rust.

- [ ] Remove all remaining nightly features
- [ ] Update our Continuous Integration (CI) to use the stable version of Rust
  - Currently, we're using `nightly-2023-10-15`. Search for this throughout the project and replace it with the stable version.

**Comment by katyo** [comment]
@M-Adoo It sounds really good for me. I hope to use ribir with stable rust in my projects soon.

**Comment by M-Adoo** [comment]
@katyo  I'm sorry for the late reply. It's great to hear that you want to use this in your project. Moving to stable Rust shouldn't be too difficult. However, I'm currently working on tasks that will cause break changes, and I want to finish these first. If you're up for it, you could try it out and let me know if you run into any problems. I'm here to help, and please don't worry if you don't have the time.

**Comment by M-Adoo** [comment]
closed by #552
