### ISSUE TITLE
Dark / Light mode confusion, unreadable docs, dark gray on black background.

### ISSUE THREAD

**Issue by rseymour** [RibirX/Ribir#524]
This is about:
- [ ] A typo 
- [ ] Innaccurate/misleading documentation (e.g. technically incorrect advice)
- [ ] Undocumented code
- [ ] Outdated documentation
- [x] Other

**Problem**
<img width="1480" alt="image" src="https://github.com/RibirX/Ribir/assets/105805/4c542942-f547-408c-a4d3-8e999517199b">

Main page seems to have a dark mode / light mode issue.  Shown in image is chrome and safari on mac.  It's unreadable. Visible on: https://ribir.org/docs/introduction

I'd just like to read the docs.

**Questionaire** _(Optional)_
- [ ] I'd like to write this documentation
- [ ] I'd like to write this documentation but I'm not sure what's needed
- [x] I don't have time to add this right now, but maybe later

**Comment by wjian23** [comment]
Thank you for your issue @rseymour, it really affects reading. we'll fix it soon.

**Comment by wjian23** [comment]
@rseymour We had set the mode fixed to light, hope you can comfortably reading.
