### ISSUE TITLE
Bugs in the todos example

### ISSUE THREAD

**Issue by STPR** [RibirX/Ribir#605]
Hello,
I'm actually testing ribir so I've compiled the todos example in Rust 1.79 under Windows 10 and I've found some bugs:
- The app almost always crash when I click a checkbox with the following error:
```
thread 'main' panicked at .\.cargo\registry\src\index.crates.io\euclid-0.22.10\src\size.rs:323:25:
called `Option::unwrap()` on a `None` value
```

- The app crash when I'm resizing the window at the minimum height with the following error:
```
thread 'main' panicked at wgpu_impl.rs:774:3:
assertion failed: !textures.is_empty()
```

**Comment by M-Adoo** [comment]
Thank you for your report. To assist us in reproducing the issue, could you please provide the following information?

- The version of Ribir you are currently using. 
- The complete stack trace of the error. You can obtain this by running `RUST_BACKTRACE=1 cargo run -p todos`.

**Comment by STPR** [comment]
It was the v0.3.0-alpha.5 but I've just tested the v0.4.0-alpha.2 and the 2 bugs are corrected.
There are still some (new tasks or checkboxes's states aren't saved after closing the app) but it doesn't crash...

**Comment by M-Adoo** [comment]
> It was the v0.3.0-alpha.5 but I've just tested the v0.4.0-alpha.2 and the 2 previous bugs are corrected. There are still some (sometimes, new tasks or checkboxes's states aren't saved after closing the app) but it doesn't crash...

Thank you. This may be the expected behavior. The state is not saved immediately because the save operation is debounced with a 5-second delay.

**Comment by STPR** [comment]
Ok.
But you happen to do somethings then close/reopen the app before the 5sec delay, it to lose everything you've done previously.

**Comment by M-Adoo** [comment]
While this would be considered a bug in a production application, in this case, it's part of a simple app designed to demonstrate the framework's usage. The goal is to maintain the code's simplicity.
