### ISSUE TITLE
cjk text rendering not correct

### ISSUE THREAD

**Issue by tkkcc** [RibirX/Ribir#613]
**Steps To Reproduce**
run todo example on master, input chinese text, text not rendered correctly.

also because of no subpixel rendering said in https://github.com/RibirX/Ribir/discussions/608, i can see "1"s have inconsistent thinness, very different from alacritty on the left. and other gtk and qt software.

**Screenshots**
![2024-08-04_15-28](https://github.com/user-attachments/assets/db3702fa-29fa-4dbe-8416-00d739226f04)

**Environment:**
 - Ribir version: `master`
 - Rust version:  `nightly`
 - OS: archlinux, x11, 1080x1920, Xft.dpi:100

**Comment by M-Adoo** [comment]
That is not a bug, as the default font family in the theme does not support Chinese characters. You can change the font family of the text to resolve this issue.
